<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/logo.png"style="width: 15rem;" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
              <div class="form-group">
                <input type="text" value="" class="form-control" placeholder="Nome" name="nome" required>
              </div>
              
              <div class="form-group">
                <input type="email" value="" class = "form-control" placeholder="E-mail" name="email" required>
              </div>

              <div class="form-group">
                <input type="password" value="" class="form-control" placeholder="Senha" name='senha' required>
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-block"style="background-color:rgb(253, 126, 20); color:white;">Inscrever-se</button>
              <?php if($this->view->erroCadastro) { ?>
                  <small class="form-text text-danger text-center font-weight-bold">
                    Erro ao realizar cadastro, verifique se os campos foram preenchidos corretamente.
                  </small>
                
              <?php } ?>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  