<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
		  <img src="/img/logo.png"style="width: 3rem;"class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<!--<div class="perfilTopo"></div>-->

				<div class="perfilPainel position-fixed">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?=$this->view->dadosGeraisUsuario['InfoUsuario']['nome']?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?=$this->view->dadosGeraisUsuario['TotaolTweets']['total_tweet']?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?=$this->view->dadosGeraisUsuario['TotalSeguindo']['total_seguindo']?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?=$this->view->dadosGeraisUsuario['TotalSeguidores']['total_seguidores']?></span>
						</div>
					</div>
					<!-- Button trigger modal -->
					<button type="button" class="btn col" data-toggle="modal" data-target="#exampleModalCenter"  style=" background-color:rgb(253, 126, 20); color:white;">
						Dados do usuário
					</button>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<form action="/quem_seguir" method="get">
								<div class="input-group mb-3">
									<input type="text" name="pesquisarPor" class="form-control" placeholder="Quem você está procurando?">
									<div class="input-group-append">
										<button class="btn" type="submit" style=" background-color:rgb(253, 126, 20); color:white;">Procurar</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

			<?php foreach($this->view->usuarios as $indice_arr => $usuario) { ?>
				<div class="row mb-2">
					<div class="col">
						<div class="card">
							<div class="card-body">
								<div class="row">
									<div class="col-md-6">
										<?= $usuario['nome']?>
									</div>
								
									<div class="col-md-6 d-flex justify-content-end">
										<div>
										<?php if($usuario['seguindo_sn'] == 0) { ?>
											<a href="/acao?acao=seguir&&id_usuario=<?=$usuario['id']?>" 
											class="btn btn-success">Seguir</a>
										<?php } ?>
										<?php if($usuario['seguindo_sn'] != 0) { ?>
											<a href="/acao?acao=deixar_de_seguir&&id_usuario=<?=$usuario['id']?>" 
											class="btn btn-danger">Deixar de seguir</a>
										<?php } ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			<?php } ?>

		</div>
	</div>
</div>
<!--modal-->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Dados de usuário</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
	  <form action="/registrar/alterar" method="POST">
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Nome:</label>
            <input type="text" class="form-control" id="recipient-name" required="">
		  </div>
		  <div class="form-group">
            <label for="recipient-name" class="col-form-label">Email:</label>
            <input type="email" class="form-control" id="recipient-name" required="">
		  </div>
		  <div class="form-group">
            <label for="recipient-name" class="col-form-label">Nova Senha:</label>
            <input type="password" class="form-control" placeholder="Senha" id="recipient-name" required="">
		  </div>
		  <div class="form-group">
            <label for="recipient-name" class="col-form-label">Confirmar Senha:</label>
            <input type="password" class="form-control" id="recipient-name" placeholder="Senha" required="">
		  </div>
		  <button type="submit" class="btn btn-primary">Alterar</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
       
      </div>
    </div>
  </div>
</div>


