<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline" style="color:rgb(253, 126, 20);">
	  		Home
		  </a>
		  	<img src="/img/logo.png"style="width: 3rem;"class="menuIco" />
		<a class="menuItem" href="/sair" style="color:rgb(253, 126, 20);">
	  		Sair
	  	</a>
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<!--<div class="perfilTopo"></div>-->

				<div class="perfilPainel position-fixed">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome">
								<?= $this->view->info_usuario['nome']?>
							</span>
						</div>
					</div>
					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?=$this->view->total_tweets['total_tweet']?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?=$this->view->total_seguindo['total_seguindo']?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?=$this->view->total_seguidores['total_seguidores']?></span>
						</div>
						
					</div>
					<!-- Button trigger modal -->
					<button type="button" class="btn  col" data-toggle="modal" data-target="#exampleModalCenter" style=" background-color:rgb(253, 126, 20); color:white;">
						Dados do usuário
					</button>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form action="/tweet" method="post">
						<textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="tweet"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn" style=" background-color:rgb(253, 126, 20); color:white;">Tweet</button>
						</div>

					</form>
				</div>
			</div>
			<div class="row">
				<div class="col-md-10">
					<div class="col-md-10" id="conteudo"></div>
				</div>
			</div>


			<?php foreach($this->view->tweets as $id_tweet => $tweet) { ?>

				<div class="row tweet">
					<div class="col">
						<p><strong><?=$tweet['nome']?></strong> <span class="text text-muted"> - <?=$tweet['data']?></span></p>
						<p><?=$tweet['tweet']?></p>
						
						<br />
						<div class="col d-flex justify-content-start">

							<a href="/acao_tweet?acao=curtir&&id=<?=$tweet['id']?>"class="btn btn-primary" style="padding-right: 15px" >
								<i class="fas fa-thumbs-up"></i>
							</a>

							<span style="padding-right: 5px; padding-left:5px " class="text-primary font-weight-bold">
								<?=$tweet['curtir']?>
							</span>

							<a href="/acao_tweet?acao=naoCurtir&&id=<?=$tweet['id']?>"class="btn btn-danger">
								<i class="fas fa-thumbs-down"></i>
							</a>

							<span style="padding-left: 5px" class= "text-danger font-weight-bold">
								<?=$tweet['naoCurtir']?>
							</span>

						</div>
						<?php if($tweet['id_usuario'] == $_SESSION['id']) {?>
							<form action="/deleta_tweet" method="post">
								<input type="hidden" name="tweet_id" value="<?=$tweet['id']?>">
								<div class="col d-flex justify-content-end">
									<button type="submit" class="btn"  style=" background-color:rgb(253, 126, 20); color:white;"><small>Remover</small></button>
								</div>
							</form>
							<!-- Button trigger modal -->
							<div class="col d-flex justify-content-end">
							<button type="button" class="btn" data-toggle="modal" data-target="#modalTweet" style=" background-color:rgb(253, 126, 20); color:white;">
								<small> Alterar </small>
							</button>
							</div>
							
						<?php }?>
					</div>
				</div>

			<?php } ?>
		</div>


		<div class="col-md-3">
			<div class="quemSeguir position-fixed">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
			
		</div>
		

	</div>
</div>
<!--modal-->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Dados de usuário</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
	  <form action="#" method="POST">
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Nome:</label>
            <input type="text" class="form-control" id="recipient-name" required="">
		  </div>
		  <div class="form-group">
            <label for="recipient-name" class="col-form-label">Email:</label>
            <input type="email" class="form-control" id="recipient-name" required="">
		  </div>
		  <div class="form-group">
            <label for="recipient-name" class="col-form-label">Nova Senha:</label>
            <input type="password" class="form-control" placeholder="Senha" id="recipient-name" required="">
		  </div>
		  <div class="form-group">
            <label for="recipient-name" class="col-form-label">Confirmar Senha:</label>
            <input type="password" class="form-control" placeholder="Senha" id="recipient-name" required="">
		  </div>
		  <button type="submit" class="btn" style="background-color:rgb(253, 126, 20); color:white">Alterar</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
       
      </div>
    </div>
  </div>
</div>

<!--modal de tweet-->
<!--modal-->
<div class="modal fade" id="modalTweet" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Informação do Tweet</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
	  <form action="#" method="POST">
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Tweet:</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="tweet"></textarea>
		  </div>
		  <button type="submit" class="btn col" style="background-color:rgb(253, 126, 20); color:white">Alterar</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
       
      </div>
    </div>
  </div>
</div>


